### ISSUE TITLE
Submit to the App Store

### ISSUE THREAD

**Issue by deanpcmad** [caike/CodeBaseHQ#1]
Hey there,
Just seen this project after a quick Google search. Would you be interested in submitting this app to the App Store at all?
I would download and try it but I haven't purchased RubyMotion.
Thanks
Dean

**Comment by caike** [comment]
Sure. This started as just a pet project, but I'd be happy to see it in the App Store and being used by more people.
I'll start investing more time into it, so stay tuned for updates :)
